### ISSUE TITLE
New feature: convert inline image into e-mail attachement, no absolute url

### ISSUE THREAD

**Issue by ahait** [SparkPost/heml#21]
New feature proposal:
Lets say i write  img src=“x.jpg” and it converts it to inline image and attach it automatically as an inline attachment. No absolute URL. No need to look on "the internet" for the image, because it is attached in the e-mail, by heml.  No need for clicking "Load remote images"-button in your e-mail client.

If I can help somehow, let me know.

**Comment by avigoldman** [comment]
Hey @ahait!
Do you mean adding the image as a base 64 encoded value in the `src` attribute or actually attaching the image to the email?

**Comment by ahait** [comment]
Well its 2 different things, sorry for that. I am thinking about inline attached image...

**Comment by avigoldman** [comment]
This is an interesting idea to get around the remote images problem.
Unfortunately there are a few problems with this approach if I'm understanding this correctly 😕
1. Because of the [size limit for messages](https://kb.mailchimp.com/delivery/deliverability-research/gmail-is-clipping-my-email) your email is likely to get clipped if you inline your images
2. The [support for base64 encoded images](https://www.campaignmonitor.com/blog/email-marketing/2013/02/embedded-images-in-html-email/) isn't great or consistent

I don't think its best to add this as an option since it will likely cause more confusion then its worth and isn't really best practice.

If you really want this feature, I'd suggest creating a custom element (.i.e. `<embed-img />`) to use this functionality.

**Comment by ahait** [comment]
<embed-img tag is a good idea! I'll check it out.
