### ISSUE TITLE
Can't install using command line

### ISSUE THREAD

**Issue by frekyll** [SparkPost/heml#3]
When I run `npm install heml -g`, I get the following error:

```
npm ERR! code E404
npm ERR! 404 Not Found: @heml/elements@^1.0.2-0
```

I'm currently running npm version 5.5.1. This [Stack Overflow article](https://stackoverflow.com/questions/11920571/cant-install-any-packages-in-node-js-using-npm-install) might be useful in debugging the source problem. I'm not having any issues installing other npm packages.

**Comment by jgzamora** [comment]
@frekyll would you mind giving some of your environment information. I couldn't reproduce by switching to `npm@5.5.1`.  Node version and OS would be a good start. 

If I understand correctly, the article you linked looks to be about a problem with the npm registry and local solutions to bypass that problem. So not sure if it's something that would apply or be fixed in the heml package itself.

**Comment by frekyll** [comment]
@jgzamora Sorry, this issue has nothing to do with the `helm` package. There seemed to be a certificate expiration issue on my machine. I was able to resolve by running `npm set registry http://registry.npmjs.org/`.
